kind: Service
apiVersion: v1
metadata:
  name: omnicache
spec:
  selector:
    app: omnicache
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 30080
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 30443
    nodePort: 30443
  - name: admin
    protocol: TCP
    port: 31080
    nodePort: 31080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnicache
  labels:
    app: omnicache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnicache
  template:
    metadata:
      labels:
        app: omnicache
    spec:
      containers:
      - name: omnicache
        image: omnicache:latest
        env:
        - name: ALTIMETER_URL
          value: ""  # Mandatory: registers the instance with Altimeter
        - name: ALTIMETER_PW
          value: ""  # Optional: allows for automatic registration on Altimeter
        ports:
        - containerPort: 30080
        - containerPort: 30443
        - containerPort: 31080
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 30080
            scheme: HTTP
